# Generated by Django 5.2.10 on 2026-05-02 14:35

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=200)),
                ('patient_name', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=5)),
                ('units_required', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Broadcasting', 'Broadcasting'), ('Matched', 'Matched'), ('Completed', 'Completed')], default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('specialty', models.CharField(max_length=100)),
                ('contact', models.CharField(blank=True, max_length=100)),
                ('beds_available', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'NGO Hospital',
                'verbose_name_plural': 'NGO Hospitals',
                'db_table': 'NGO_Hospitals',
            },
        ),
        migrations.CreateModel(
            name='NGOProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('contact_person', models.CharField(blank=True, max_length=120)),
                ('city', models.CharField(max_length=100)),
                ('service_type', models.CharField(max_length=200)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'NGO Profile',
                'verbose_name_plural': 'NGO Profiles',
                'db_table': 'NGO_NGOProfiles',
            },
        ),
        migrations.CreateModel(
            name='SOSRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(max_length=255)),
                ('patient_name', models.CharField(default='Unknown', max_length=255)),
                ('blood_group', models.CharField(max_length=10)),
                ('units_required', models.IntegerField(default=1)),
                ('status', models.CharField(default='Pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerDonor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('blood_group', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=5)),
                ('phone', models.CharField(max_length=15)),
                ('city', models.CharField(default='Global', max_length=100)),
                ('is_available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=5)),
                ('contact_number', models.CharField(blank=True, max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='core.ngoprofile')),
            ],
            options={
                'verbose_name': 'NGO Patient Profile',
                'verbose_name_plural': 'NGO Patient Profiles',
                'db_table': 'NGO_PatientProfiles',
            },
        ),
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referral_id', models.CharField(db_index=True, default=core.models.generate_referral_id, editable=False, max_length=20, unique=True)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Treatment Started', 'Treatment Started'), ('Completed', 'Completed')], default='Pending', max_length=50)),
                ('urgency', models.CharField(choices=[('Normal', 'Normal'), ('Emergency', 'Emergency')], default='Normal', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_referrals', to='core.ngoprofile')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='core.patientprofile')),
                ('to_hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_referrals', to='core.hospital')),
            ],
            options={
                'verbose_name': 'NGO Referral',
                'verbose_name_plural': 'NGO Referrals',
                'db_table': 'NGO_Referrals',
            },
        ),
        migrations.CreateModel(
            name='ReferralNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_hospital', models.CharField(max_length=255)),
                ('specialty_required', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Request Sent', 'Request Sent'), ('Bed Reserved', 'Bed Reserved'), ('Appointment Fixed', 'Appointment Fixed'), ('Closed', 'Closed'), ('Active', 'Active (Legacy)'), ('Pending', 'Pending (Legacy)')], default='Request Sent', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('source_ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='core.ngoprofile')),
            ],
            options={
                'verbose_name': 'NGO Referral Network',
                'verbose_name_plural': 'NGO Referral Networks',
                'db_table': 'NGO_ReferralNetworks',
            },
        ),
        migrations.CreateModel(
            name='ReferralStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Treatment Started', 'Treatment Started'), ('Completed', 'Completed')], max_length=50)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('referral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='core.referral')),
            ],
            options={
                'verbose_name': 'NGO Referral Status Update',
                'verbose_name_plural': 'NGO Referral Status Updates',
                'db_table': 'NGO_ReferralStatusUpdates',
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('distance_km', models.FloatField(default=0.0)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sos_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.sosrequest')),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.volunteerdonor')),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('expert_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('description', models.TextField()),
                ('full_description', models.TextField(blank=True, default='')),
                ('image_url', models.CharField(blank=True, default='', max_length=500)),
                ('is_open', models.BooleanField(default=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('ngo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshops', to='core.ngoprofile')),
            ],
            options={
                'verbose_name': 'NGO Workshop',
                'verbose_name_plural': 'NGO Workshops',
                'db_table': 'NGO_Workshops',
            },
        ),
        migrations.CreateModel(
            name='WorkshopRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email_or_phone', models.CharField(max_length=100)),
                ('id_proof', models.FileField(blank=True, null=True, upload_to='ids/')),
                ('role', models.CharField(choices=[('patient', 'Patient/Attendee'), ('volunteer', 'Volunteer')], default='patient', max_length=20)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('verified', 'Verified')], default='confirmed', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.workshop')),
            ],
            options={
                'verbose_name': 'NGO Workshop Registration',
                'verbose_name_plural': 'NGO Workshop Registrations',
                'db_table': 'NGO_WorkshopRegistrations',
            },
        ),
    ]
