# Generated by Django 6.0.3 on 2026-05-03 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BloodMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_id', models.CharField(max_length=20, unique=True)),
                ('donor_name', models.CharField(max_length=100)),
                ('blood_group', models.CharField(max_length=5)),
                ('hospital_name', models.CharField(max_length=200)),
                ('units', models.IntegerField()),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('In Transit', 'In Transit'), ('Cancelled', 'Cancelled')], default='Completed', max_length=20)),
                ('location', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
