# Generated by Django 5.2.10 on 2026-03-31 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkshopRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email_or_phone', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('patient', 'Patient/Attendee'), ('volunteer', 'Volunteer')], default='patient', max_length=20)),
                ('registered_at', models.DateTimeField(auto_now_add=True)),
                ('workshop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='core.workshop')),
            ],
        ),
    ]
