# Generated by Django 6.0.3 on 2026-05-03 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_bloodmatch'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerdonor',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], default='Pending', max_length=20),
        ),
    ]
