# Generated by Django 5.2.10 on 2026-03-31 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_workshopregistration"),
    ]

    operations = [
        migrations.AddField(
            model_name="workshopregistration",
            name="status",
            field=models.CharField(
                choices=[("confirmed", "Confirmed"), ("verified", "Verified")],
                default="confirmed",
                max_length=20,
            ),
        ),
    ]

