# Generated by Django 6.0.3 on 2026-05-03 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_volunteerdonor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerdonor',
            name='hospital_name',
            field=models.CharField(blank=True, default='City Hospital', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='volunteerdonor',
            name='units',
            field=models.IntegerField(default=1),
        ),
    ]
