# Generated by Django 5.2.10 on 2026-03-31 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_workshopregistration_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referralnetwork',
            name='status',
            field=models.CharField(choices=[('Request Sent', 'Request Sent'), ('Bed Reserved', 'Bed Reserved'), ('Appointment Fixed', 'Appointment Fixed'), ('Closed', 'Closed'), ('Active', 'Active (Legacy)'), ('Pending', 'Pending (Legacy)')], default='Request Sent', max_length=50),
        ),
    ]
