# Generated by Django 6.0.3 on 2026-05-03 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_volunteerdonor_hospital_name_volunteerdonor_units'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerdonor',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Transit', 'In Transit'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Pending', max_length=20),
        ),
    ]
