# Generated by Django 5.2.10 on 2026-04-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_hospital_referral_referralstatusupdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshopregistration',
            name='id_proof',
            field=models.FileField(blank=True, null=True, upload_to='ids/'),
        ),
    ]
