# Generated by Django 5.2.10 on 2026-04-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_workshopregistration_id_proof'),
    ]

    operations = [
        migrations.AddField(
            model_name='ngoprofile',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='ngoprofile',
            name='contact_person',
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
