# Generated by Django 5.2.10 on 2026-04-01 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_donor_donation'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='ngo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='donations', to='core.ngoprofile'),
        ),
    ]
