# Generated by Django 6.0.3 on 2026-06-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_volunteerdonor_mission_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerdonor',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='volunteerdonor',
            name='whatsapp_consent',
            field=models.BooleanField(default=False),
        ),
    ]
