# Generated by Django 5.2.10 on 2026-04-03 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_workshop_latitude_workshop_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='beds_available',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
