# Generated by Django 6.0.3 on 2026-06-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_volunteerdonor_is_approved_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerdonor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
