# Generated by Django 5.2.10 on 2026-04-08 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_hospital_beds_available'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-date'], 'verbose_name': 'Donation', 'verbose_name_plural': 'Donations'},
        ),
        migrations.AlterModelOptions(
            name='donor',
            options={'verbose_name': 'Donor', 'verbose_name_plural': 'Donors'},
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name': 'Hospital', 'verbose_name_plural': 'Hospitals'},
        ),
        migrations.AlterModelOptions(
            name='ngoprofile',
            options={'verbose_name': 'NGO Profile', 'verbose_name_plural': 'NGO Profiles'},
        ),
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'verbose_name': 'Patient Profile', 'verbose_name_plural': 'Patient Profiles'},
        ),
        migrations.AlterModelOptions(
            name='referral',
            options={'verbose_name': 'Referral', 'verbose_name_plural': 'Referrals'},
        ),
        migrations.AlterModelOptions(
            name='referralnetwork',
            options={'verbose_name': 'Referral Network', 'verbose_name_plural': 'Referral Networks'},
        ),
        migrations.AlterModelOptions(
            name='referralstatusupdate',
            options={'verbose_name': 'Referral Status Update', 'verbose_name_plural': 'Referral Status Updates'},
        ),
        migrations.AlterModelOptions(
            name='workshop',
            options={'verbose_name': 'Workshop', 'verbose_name_plural': 'Workshops'},
        ),
        migrations.AlterModelOptions(
            name='workshopregistration',
            options={'verbose_name': 'Workshop Registration', 'verbose_name_plural': 'Workshop Registrations'},
        ),
        migrations.AlterModelTable(
            name='donation',
            table='NGO_Donations',
        ),
        migrations.AlterModelTable(
            name='donor',
            table='NGO_Donors',
        ),
        migrations.AlterModelTable(
            name='hospital',
            table='NGO_Hospitals',
        ),
        migrations.AlterModelTable(
            name='ngoprofile',
            table='NGO_NGOProfiles',
        ),
        migrations.AlterModelTable(
            name='patientprofile',
            table='NGO_PatientProfiles',
        ),
        migrations.AlterModelTable(
            name='referral',
            table='NGO_Referrals',
        ),
        migrations.AlterModelTable(
            name='referralnetwork',
            table='NGO_ReferralNetworks',
        ),
        migrations.AlterModelTable(
            name='referralstatusupdate',
            table='NGO_ReferralStatusUpdates',
        ),
        migrations.AlterModelTable(
            name='workshop',
            table='NGO_Workshops',
        ),
        migrations.AlterModelTable(
            name='workshopregistration',
            table='NGO_WorkshopRegistrations',
        ),
    ]
