# Generated by Django 5.2.10 on 2026-04-08 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_donation_options_alter_donor_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-date'], 'verbose_name': 'NGO Donation', 'verbose_name_plural': 'NGO Donations'},
        ),
        migrations.AlterModelOptions(
            name='donor',
            options={'verbose_name': 'NGO Donor', 'verbose_name_plural': 'NGO Donors'},
        ),
        migrations.AlterModelOptions(
            name='hospital',
            options={'verbose_name': 'NGO Hospital', 'verbose_name_plural': 'NGO Hospitals'},
        ),
        migrations.AlterModelOptions(
            name='patientprofile',
            options={'verbose_name': 'NGO Patient Profile', 'verbose_name_plural': 'NGO Patient Profiles'},
        ),
        migrations.AlterModelOptions(
            name='referral',
            options={'verbose_name': 'NGO Referral', 'verbose_name_plural': 'NGO Referrals'},
        ),
        migrations.AlterModelOptions(
            name='referralnetwork',
            options={'verbose_name': 'NGO Referral Network', 'verbose_name_plural': 'NGO Referral Networks'},
        ),
        migrations.AlterModelOptions(
            name='referralstatusupdate',
            options={'verbose_name': 'NGO Referral Status Update', 'verbose_name_plural': 'NGO Referral Status Updates'},
        ),
        migrations.AlterModelOptions(
            name='workshop',
            options={'verbose_name': 'NGO Workshop', 'verbose_name_plural': 'NGO Workshops'},
        ),
        migrations.AlterModelOptions(
            name='workshopregistration',
            options={'verbose_name': 'NGO Workshop Registration', 'verbose_name_plural': 'NGO Workshop Registrations'},
        ),
    ]
