# Generated by Django 6.0.3 on 2026-06-16 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_donor_donation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='hospital_type',
            field=models.CharField(choices=[('govt', 'Government'), ('private', 'Private')], default='govt', max_length=10),
        ),
        migrations.AddField(
            model_name='hospital',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='hospital',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hospital',
            name='license_no',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
        migrations.AddField(
            model_name='hospital',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
