# Generated by Django 5.2.10 on 2026-04-08 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_donation_options_alter_donor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='full_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='workshop',
            name='image_url',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
