# Generated by Django 6.0.3 on 2026-06-16 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_hospital_created_at_hospital_hospital_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='license_no',
            field=models.CharField(default='UNKNOWN', max_length=100),
        ),
    ]
