# Generated by Django 6.0.3 on 2026-04-25 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_bloodbank_registry_transferlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blooddonation',
            name='donor',
        ),
        migrations.DeleteModel(
            name='BloodRequest',
        ),
        migrations.DeleteModel(
            name='BloodStock',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='donor',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='ngo',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='workshop',
        ),
        migrations.DeleteModel(
            name='TransferLog',
        ),
        migrations.DeleteModel(
            name='BloodDonation',
        ),
        migrations.DeleteModel(
            name='DonorRegistry',
        ),
        migrations.DeleteModel(
            name='Donor',
        ),
        migrations.DeleteModel(
            name='Donation',
        ),
    ]
