# Generated by Django 6.0.3 on 2026-07-24 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_hospital_lat_hospital_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hospital',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='hospital',
            name='lng',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
    ]
