# Generated by Django 6.0.3 on 2026-04-28 07:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_sosrequest_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='sosrequest',
            name='blood_group',
            field=models.CharField(default='B+', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sosrequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sosrequest',
            name='patient_name',
            field=models.CharField(default='Unknown', max_length=255),
        ),
        migrations.AddField(
            model_name='sosrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='sosrequest',
            name='units_required',
            field=models.IntegerField(default=1),
        ),
    ]
